/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
      "surface-bright": "#f8f9ff",
      "surface-dim": "#cbdbf5",
      "surface-container-low": "#eff4ff",
      "primary": "#b70f30",
      "on-secondary": "#ffffff",
      "error-container": "#ffdad6",
      "tertiary": "#595c5e",
      "on-surface": "#0b1c30",
      "on-background": "#0b1c30",
      "secondary-container": "#d5e3fd",
      "on-tertiary-fixed": "#191c1e",
      "background": "#f8f9ff",
      "on-primary-fixed": "#400009",
      "inverse-primary": "#ffb3b3",
      "on-secondary-fixed": "#0d1c2f",
      "surface-container-lowest": "#ffffff",
      "outline-variant": "#e3bebd",
      "tertiary-fixed": "#e0e3e5",
      "tertiary-container": "#727577",
      "tertiary-fixed-dim": "#c4c7c9",
      "on-secondary-fixed-variant": "#3a485c",
      "outline": "#8f6f6f",
      "surface": "#f8f9ff",
      "inverse-on-surface": "#eaf1ff",
      "on-primary-fixed-variant": "#920021",
      "on-secondary-container": "#57657b",
      "on-tertiary-container": "#fbfdff",
      "surface-container": "#e5eeff",
      "secondary-fixed-dim": "#b9c7e0",
      "secondary": "#515f74",
      "surface-container-highest": "#d3e4fe",
      "surface-variant": "#d3e4fe",
      "on-primary-container": "#fffbff",
      "surface-tint": "#bb1332",
      "error": "#ba1a1a",
      "surface-container-high": "#dce9ff",
      "primary-fixed": "#ffdad9",
      "primary-fixed-dim": "#ffb3b3",
      "primary-container": "#db3045",
      "secondary-fixed": "#d5e3fd",
      "on-tertiary": "#ffffff",
      "on-error": "#ffffff",
      "on-error-container": "#93000a",
      "on-surface-variant": "#5b4040",
      "on-primary": "#ffffff",
      "on-tertiary-fixed-variant": "#444749",
      "inverse-surface": "#213145"
      },
      fontFamily: {
        "sans": ["'Hanken Grotesk'", "sans-serif"],
        "mono": ["'JetBrains Mono'", "monospace"],
      },
      spacing: {
      "base": "4px",
      "xs": "8px",
      "lg": "40px",
      "margin-mobile": "16px",
      "xl": "64px",
      "sm": "16px",
      "md": "24px",
      "gutter": "24px",
      "container-max": "1280px"
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }]
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
