services:
  # 1. Base de données PostgreSQL avec pgvector inclus
  postgres-db:
    image: ankane/pgvector:latest # Image cruciale : contient déjà pgvector pour la Phase 3
    container_name: certifhub_db
    environment:
      POSTGRES_USER: certif_user
      POSTGRES_PASSWORD: certif_password
      POSTGRES_DB: certifhub_db
    ports:
      - "5432:5432" # Expose le port pour que Spring Boot (en local) puisse s'y connecter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. Outil de visualisation web
  pgadmin:
    image: dpage/pgadmin4
    container_name: certifhub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@devoteam.com
      PGADMIN_DEFAULT_PASSWORD: seddik
    ports:
      - "5050:80" # Accessible sur http://localhost:5050
    depends_on:
      - postgres-db
    restart: unless-stopped

  # 3. Serveur de messagerie RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: certifhub_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # Port de communication TCP (utilisé par Spring Boot)
      - "15672:15672" # Port de l'interface web (accessible sur http://localhost:15672)
    restart: unless-stopped

volumes:
  postgres_data:
