---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	rewrite(rewrite)
	guardrail(guardrail)
	off_topic_response(off_topic_response)
	route(route)
	text_to_sql(text_to_sql)
	vector_search(vector_search)
	grade_retrieval(grade_retrieval)
	web_scrape(web_scrape)
	generate(generate)
	groundedness(groundedness)
	regenerate(regenerate)
	__end__([<p>__end__</p>]):::last
	__start__ --> rewrite;
	generate --> groundedness;
	grade_retrieval -.-> generate;
	grade_retrieval -.-> web_scrape;
	groundedness -. &nbsp;done&nbsp; .-> __end__;
	groundedness -.-> regenerate;
	guardrail -.-> off_topic_response;
	guardrail -.-> route;
	regenerate --> groundedness;
	rewrite --> guardrail;
	route -.-> text_to_sql;
	route -.-> vector_search;
	text_to_sql --> generate;
	vector_search --> grade_retrieval;
	web_scrape --> generate;
	off_topic_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
